port module Port exposing (fromElm, toElm, decodeFlags)

{-| This file was generated by elm-ts-interop init. You can manually edit this file,
just avoid exposing the low-level ports to ensure that only the FromElm and ToElm types
can be sent/received by your ports.

@docs fromElm, toElm, decodeFlags

-}

import Json.Decode
import Json.Encode
import PortDefinition
import TsJson.Decode as TsDecode
import TsJson.Encode as TsEncode


{-| -}
fromElm : PortDefinition.FromElm -> Cmd msg
fromElm value =
    value
        |> (PortDefinition.interop.fromElm |> TsEncode.encoder)
        |> interopFromElm


{-| -}
toElm : Sub (Result Json.Decode.Error PortDefinition.ToElm)
toElm =
    (PortDefinition.interop.toElm |> TsDecode.decoder)
        |> Json.Decode.decodeValue
        |> interopToElm


{-| -}
decodeFlags : Json.Decode.Value -> Result Json.Decode.Error PortDefinition.Flags
decodeFlags flags =
    Json.Decode.decodeValue
        (PortDefinition.interop.flags |> TsDecode.decoder)
        flags



-- internals - do not expose


port interopFromElm : Json.Encode.Value -> Cmd msg


port interopToElm : (Json.Decode.Value -> msg) -> Sub msg
